POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "ReactJS",
    "description": "Esse é um novo video",
    "duration": 180
}
###

GET http://localhost:3333/videos
###

GET http://localhost:3333/videos?search=Node
###

PUT http://localhost:3333/videos/5fb2e96d-31d4-4bd3-824f-a133b817d8e2
Content-Type: application/json

{
    "title": "ReactJS",
    "description": "Novo video Reactjs",
    "duration": 180
}
###
DELETE  http://localhost:3333/videos/5fb2e96d-31d4-4bd3-824f-a133b817d8e2