POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Node 3",
    "description": "Esse é o terceiro video",
    "duration": 180
}
###

GET http://localhost:3333/videos
###

GET http://localhost:3333/videos?search=Node
###

PUT http://localhost:3333/videos/4c2fa05d-f27a-4192-a0ca-ed44cbffbb9f
Content-Type: application/json

{
    "title": "Video ReactJS",
    "description": "Novo video Reactjs",
    "duration": 180
}
###
DELETE  http://localhost:3333/videos/a51180e0-b991-4ada-84e2-c0cdeeb99be9


